package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

const mainHelp = `NodeManage Agent %s

Usage:
  nodemanage-agent <command> [options]

Commands:
  install      Install and register Agent runtimes and services
  run          Run the continuous configuration sync loop
  once         Run one configuration sync cycle
  repair       Repair binaries, configuration layout and services
  upgrade      Upgrade managed binaries with automatic rollback
  diagnose     Print a local diagnostic report
  status       Print versions, services and configuration status
  logs         Print recent component logs
  uninstall    Remove services and binaries; configuration is retained by default
  version      Print the Agent version
  help         Show general or command-specific help

Run 'nodemanage-agent help <command>' for command options.
System installations normally require sudo; user installations must run without sudo.
`

var commandHelpText = map[string]string{
	"help": `Usage: nodemanage-agent help [command]

Shows the general command list or detailed usage for one command.
`,
	"install": `Usage: nodemanage-agent install --server URL --ticket TICKET --name NAME [options]

Installs verified Agent and runtime artifacts, registers the VPS, and creates services.
Normally invoked through the installation command generated by the management panel.

Options:
  --mode auto|system|user
  --manifest URL
  --ingress-mode direct|cloudflare_tunnel
  --tunnel-kind none|quick|named
  --tunnel-hostname HOSTNAME
  --tunnel-token TOKEN
  --origin-port PORT
  --connect-port PORT
`,
	"run": `Usage: nodemanage-agent run [--config PATH]

Runs the long-lived sync, certificate, and Tunnel maintenance loop.
Normally started by systemd, OpenRC, or the standalone process manager.
`,
	"once": `Usage: nodemanage-agent once [--config PATH]

Runs exactly one maintenance and configuration sync cycle, then exits.
`,
	"repair": `Usage: nodemanage-agent repair [--manifest URL]

Repairs missing or damaged binaries, A/B configuration links, permissions, and services.
Run as root for a system installation or as the original user for a user installation.
`,
	"upgrade": `Usage: nodemanage-agent upgrade [--manifest URL]

Upgrades Agent, sing-box, and cloudflared when applicable. Failed health checks restore
the previous verified binaries.
`,
	"diagnose": `Usage: nodemanage-agent diagnose [--full] [--mode auto|system|user]

Prints a redacted JSON diagnostic report. --full adds local versions, permissions,
configuration validation, and the active revision. It does not change the system.
`,
	"status": `Usage: nodemanage-agent status [--mode auto|system|user]

Prints a redacted JSON summary of versions, services, ingress, Tunnel, and revision state.
`,
	"logs": `Usage: nodemanage-agent logs [--component agent|sing-box|tunnel|install] [--tail N] [--mode auto|system|user]

Prints recent logs without uploading them. N defaults to 200 and is limited to 2000.
`,
	"uninstall": `Usage: nodemanage-agent uninstall [--mode auto|system|user] [--purge]

Stops services and removes managed binaries. Configuration is retained unless --purge
is supplied. --purge permanently deletes NodeManage configuration, state, and backups.
`,
	"version": `Usage: nodemanage-agent version

Prints the installed Agent version.
`,
}

func commandHelp(command string) string {
	command = strings.TrimSpace(command)
	if command == "" {
		return fmt.Sprintf(mainHelp, version)
	}
	if text, ok := commandHelpText[command]; ok {
		return text
	}
	return fmt.Sprintf("Unknown command %q.\n\n%s", command, fmt.Sprintf(mainHelp, version))
}

func commandLayout(modeFlag string) (installLayout, error) {
	mode, err := resolveInstallMode(modeFlag)
	if err != nil {
		return installLayout{}, err
	}
	return layoutForMode(mode)
}

func readAgentConfig(layout installLayout) (config, installLayout, error) {
	data, err := os.ReadFile(layout.AgentConfig)
	if err != nil {
		return config{}, layout, err
	}
	var cfg config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return config{}, layout, err
	}
	resolved, err := layoutFromConfig(cfg)
	if err != nil {
		return config{}, layout, err
	}
	return cfg, resolved, nil
}

func statusCommand(args []string) {
	flags := flag.NewFlagSet("status", flag.ExitOnError)
	modeFlag := flags.String("mode", "auto", "installation mode: auto, system or user")
	_ = flags.Parse(args)
	layout, err := commandLayout(*modeFlag)
	if err != nil {
		fatal("[NM-E241] " + err.Error())
	}
	cfg, layout, err := readAgentConfig(layout)
	if err != nil {
		fatal("[NM-E241] read Agent configuration: " + err.Error())
	}
	result := map[string]any{
		"agent_version":       version,
		"sing_box_version":    commandOutput(layout.SingBoxPath, "version"),
		"cloudflared_version": commandOutput(layout.CloudflaredPath, "version"),
		"install_mode":        cfg.InstallMode,
		"init_system":         cfg.InitSystem,
		"ingress_mode":        cfg.IngressMode,
		"current_revision":    readRevision(cfg.RuntimePath + ".revision"),
		"services": map[string]bool{
			"agent":    serviceActive(cfg.InitSystem, cfg.InstallMode, "nodemanage-agent"),
			"sing_box": serviceActive(cfg.InitSystem, cfg.InstallMode, "sing-box"),
			"tunnel":   cfg.IngressMode == "cloudflare_tunnel" && tunnelActive(cfg),
		},
		"configuration": map[string]any{
			"agent_readable":   canOpen(layout.AgentConfig, os.O_RDONLY),
			"runtime_readable": canOpen(cfg.RuntimePath, os.O_RDONLY),
			"runtime_valid":    commandOK(layout.SingBoxPath, "check", "-c", cfg.RuntimePath),
		},
	}
	if cfg.IngressMode == "cloudflare_tunnel" {
		result["tunnel"] = map[string]any{"kind": cfg.TunnelKind, "hostname": cfg.TunnelHostname, "connect_port": cfg.TunnelConnectPort, "origin_port": cfg.TunnelOriginPort}
	}
	printJSON(result)
}

func diagnoseCommand(args []string) {
	flags := flag.NewFlagSet("diagnose", flag.ExitOnError)
	full := flags.Bool("full", false, "include versions, permissions and configuration validation")
	modeFlag := flags.String("mode", "auto", "installation mode: auto, system or user")
	_ = flags.Parse(args)
	layout, err := commandLayout(*modeFlag)
	if err != nil {
		fatal("[NM-E242] " + err.Error())
	}
	platform := detectPlatform()
	platform.InstallMode = layout.Mode
	cfg, resolved, configErr := readAgentConfig(layout)
	if configErr == nil {
		layout = resolved
		platform.InstallMode = cfg.InstallMode
	}
	result := map[string]any{
		"platform":              platform,
		"is_root":               os.Geteuid() == 0,
		"agent_installed":       commandOK(layout.AgentPath, "version"),
		"sing_box_installed":    commandOK(layout.SingBoxPath, "version"),
		"cloudflared_installed": commandOK(layout.CloudflaredPath, "version"),
		"agent_config":          fileExists(layout.AgentConfig),
		"runtime_config":        fileExists(layout.RuntimeConfig),
		"agent_running":         serviceActive(platform.InitSystem, layout.Mode, "nodemanage-agent"),
		"sing_box_running":      serviceActive(platform.InitSystem, layout.Mode, "sing-box"),
		"paths":                 map[string]string{"agent": layout.AgentPath, "sing_box": layout.SingBoxPath, "cloudflared": layout.CloudflaredPath, "config": layout.AgentConfig, "runtime": layout.RuntimeConfig, "state": layout.StateRoot},
	}
	if configErr != nil {
		result["configuration_error"] = configErr.Error()
	}
	if *full {
		result["versions"] = map[string]string{"agent": commandOutput(layout.AgentPath, "version"), "sing_box": commandOutput(layout.SingBoxPath, "version"), "cloudflared": commandOutput(layout.CloudflaredPath, "version")}
		result["service_control"] = serviceControlAvailable(platform.InitSystem, layout.Mode)
		result["permissions"] = map[string]any{"agent_config_readable": canOpen(layout.AgentConfig, os.O_RDONLY), "runtime_config_readable": canOpen(layout.RuntimeConfig, os.O_RDONLY), "runtime_config_writable": canOpen(layout.RuntimeConfig, os.O_WRONLY)}
		result["runtime_config_valid"] = commandOK(layout.SingBoxPath, "check", "-c", layout.RuntimeConfig)
		result["current_revision"] = readRevision(layout.RuntimeConfig + ".revision")
		if configErr == nil {
			result["ingress_mode"] = cfg.IngressMode
			result["tunnel_running"] = cfg.IngressMode == "cloudflare_tunnel" && tunnelActive(cfg)
		}
	}
	printJSON(result)
}

func logsCommand(args []string) {
	flags := flag.NewFlagSet("logs", flag.ExitOnError)
	component := flags.String("component", "agent", "component: agent, sing-box, tunnel or install")
	tail := flags.Int("tail", 200, "number of recent lines (1-2000)")
	modeFlag := flags.String("mode", "auto", "installation mode: auto, system or user")
	_ = flags.Parse(args)
	if *tail < 1 || *tail > 2000 {
		fatal("[NM-E243] --tail must be between 1 and 2000")
	}
	if *component != "agent" && *component != "sing-box" && *component != "tunnel" && *component != "install" {
		fatal("[NM-E243] --component must be agent, sing-box, tunnel or install")
	}
	layout, err := commandLayout(*modeFlag)
	if err != nil {
		fatal("[NM-E243] " + err.Error())
	}
	cfg, resolved, configErr := readAgentConfig(layout)
	if configErr == nil {
		layout = resolved
	}
	if *component == "install" {
		printLogTail(layout.LogPath, *tail)
		return
	}
	if *component == "tunnel" {
		path := filepath.Join(layout.StateRoot, "cloudflared.log")
		if configErr == nil {
			path = tunnelLogPath(cfg)
		}
		printLogTail(path, *tail)
		return
	}
	if configErr != nil {
		fatal("[NM-E243] read Agent configuration: " + configErr.Error())
	}
	if cfg.InitSystem == "systemd" {
		unit := *component + ".service"
		if *component == "agent" {
			unit = "nodemanage-agent.service"
		}
		journalArgs := []string{"--no-pager", "-n", strconv.Itoa(*tail), "-u", unit}
		if cfg.InstallMode == "user" {
			journalArgs = append([]string{"--user"}, journalArgs...)
		}
		output, err := exec.Command("journalctl", journalArgs...).CombinedOutput()
		if err != nil {
			fatal("[NM-E243] journalctl: " + strings.TrimSpace(string(output)))
		}
		fmt.Print(string(output))
		return
	}
	if cfg.InitSystem == "standalone" {
		name := *component
		if name == "agent" {
			name = "nodemanage-agent"
		}
		printLogTail(filepath.Join(layout.StateRoot, name+".log"), *tail)
		return
	}
	if cfg.InitSystem == "openrc" {
		name := *component
		if name == "agent" {
			name = "nodemanage-agent"
		}
		output, err := exec.Command("rc-service", name, "status").CombinedOutput()
		if err != nil && len(output) == 0 {
			fatal("[NM-E243] OpenRC service status unavailable")
		}
		fmt.Print(string(output))
		fmt.Println("OpenRC service output is managed by the host logger; use the system log for historical entries.")
		return
	}
	fatal("[NM-E243] unsupported init system: " + cfg.InitSystem)
}

func printJSON(value any) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		fatal(err.Error())
	}
	fmt.Println(string(data))
}

func printLogTail(path string, lines int) {
	text, err := readLogTail(path, lines, 2<<20)
	if err != nil {
		fatal("[NM-E243] read log: " + err.Error())
	}
	fmt.Print(text)
	if text != "" && !strings.HasSuffix(text, "\n") {
		fmt.Println()
	}
}

func readLogTail(path string, lines, maxBytes int) (string, error) {
	if lines < 1 || maxBytes < 1 {
		return "", errors.New("invalid tail limits")
	}
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil {
		return "", err
	}
	start := info.Size() - int64(maxBytes)
	if start < 0 {
		start = 0
	}
	if _, err := file.Seek(start, io.SeekStart); err != nil {
		return "", err
	}
	data, err := io.ReadAll(io.LimitReader(file, int64(maxBytes)))
	if err != nil {
		return "", err
	}
	text := string(data)
	endsWithNewline := strings.HasSuffix(text, "\n")
	parts := strings.Split(text, "\n")
	if start > 0 && len(parts) > 1 {
		parts = parts[1:]
	}
	contentLines := len(parts)
	if endsWithNewline {
		contentLines--
	}
	if contentLines > lines {
		parts = parts[contentLines-lines:]
	}
	return strings.Join(parts, "\n"), nil
}
