// Generated by scripts/generate-release-manifest.mjs. Do not edit.
export const AGENT_VERSION = "0.5.0";
export const SING_BOX_VERSION = "1.13.12";
export const RELEASE_DIGESTS = {
  "amd64": {
    "agentSha256": "cb83172b4ebc995e0fa1b5d36e4ba4a6adf210e45440faea5dba3c53fdfc3483",
    "singBoxSha256": "1540533adb3df24f5ad5f14b5c7ca3dbc2401b10a1c1eb278fcadcada47ec6c4"
  },
  "arm64": {
    "agentSha256": "d8cfe85f97ecdff2af4155bfb75cc1829c35ce1d9a0294d1e191cc332341ab1c",
    "singBoxSha256": "1ffa3b48ad6fa98f9fd810482e39bdd5b6157782ef11ce37d67bdcfd9338547a"
  }
} as const;
