// Generated by scripts/generate-release-manifest.mjs. Do not edit.
export const AGENT_VERSION = "0.4.0";
export const SING_BOX_VERSION = "1.13.12";
export const RELEASE_DIGESTS = {
  "amd64": {
    "agentSha256": "ee0203d9e5a338df12a511f9de84e175189a6b2e7bb1c4a0b8fedaf67b0e0088",
    "singBoxSha256": "1540533adb3df24f5ad5f14b5c7ca3dbc2401b10a1c1eb278fcadcada47ec6c4"
  },
  "arm64": {
    "agentSha256": "4bb3d94af33d70d1fa79c05b3ed9e13148cc9cf38beca0e353fe573a56ee8561",
    "singBoxSha256": "1ffa3b48ad6fa98f9fd810482e39bdd5b6157782ef11ce37d67bdcfd9338547a"
  }
} as const;
