// Generated by scripts/generate-release-manifest.mjs. Do not edit.
export const AGENT_VERSION = "0.11.0";
export const SING_BOX_VERSION = "1.13.12";
export const CLOUDFLARED_VERSION = "2026.8.2";
export const RELEASE_DIGESTS = {
  "amd64": {
    "agentSha256": "3e3930e6b842f323d721a48b544788cfde39ae28cf83d2713e6191a6a96b5af5",
    "singBoxSha256": "1540533adb3df24f5ad5f14b5c7ca3dbc2401b10a1c1eb278fcadcada47ec6c4",
    "cloudflaredSha256": "fcfb02b575a52ca1af2e3267af4e1517bcdeb30ac48c834c69abaed3c0576ad2"
  },
  "arm64": {
    "agentSha256": "27f8350b41b0498cc3be2c2f443e6e072313e5441f7d1eadd248ffbfb5b0d636",
    "singBoxSha256": "1ffa3b48ad6fa98f9fd810482e39bdd5b6157782ef11ce37d67bdcfd9338547a",
    "cloudflaredSha256": "7747d94570fb390cf47dcb4f9555c193c6355cda9793f0d878d9049e5d6a7790"
  }
} as const;
